//### with json param
//POST http://localhost:8080/employees
//Content-Type: application/json
//
//{"name": "Samwise Gamgee", "role": "gardener"}

//PUT http://localhost:8080/employees/3
//Content-Type: application/json
//
//{"name": "Samwise Gamgee", "role": "ring bearer", "id": 3}


DELETE http://localhost:8080/employees/1
Content-Type: application/json
